### ISSUE TITLE
types in readme

### ISSUE THREAD

**Issue by admsasha** [antongus/stm32-ld-scripts#1]
>     CHIP  = STM32F10X_MD_VL
> ...
>     LD_SCRIPT   = $(CHIP).ld
>     LD_SCRIPT_PATH  = ld-scripts
> ...
>     LD_FLAGS    += -L$(LD_SCRIPTS)
>     LD_FLAGS    += -T$(LD_SCRIPT)

can be:
>      LD_FLAGS    += -L$(LD_SCRIPT_PATH)

**Comment by antongus** [comment]
Thanks!
Fixed.
